
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FireBaseGetSampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FireBaseGetSampleApp
pod 'Firebase'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Database'
  target 'FireBaseGetSampleAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FireBaseGetSampleAppUITests' do
    # Pods for testing
  end

end
