# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseGetSampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseGetSampleApp
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase'
pod 'Firebase/Core'
  target 'FirebaseGetSampleAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FirebaseGetSampleAppUITests' do
    # Pods for testing
  end

end
