# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GetSampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GetSampleApp
pod 'Firebase/Database'
pod 'Firebase/Core'
pod 'Firebase/Firestore'
  target 'GetSampleAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GetSampleAppUITests' do
    # Pods for testing
  end

end
