# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseSignInSampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseSignInSampleApp
pod 'Firebase'
pod 'Firebase/Database'
pod 'Firebase/Auth'

  target 'FirebaseSignInSampleAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FirebaseSignInSampleAppUITests' do
    # Pods for testing
  end

end
