# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FireBaseSampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FireBaseSampleApp
pod 'Firebase'
pod 'Firebase/Auth'
pod 'Firebase/Database'

  target 'FireBaseSampleAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FireBaseSampleAppUITests' do
    # Pods for testing
  end

end
